version: "3"

services:
  fastapi:
    container_name: fastapi_container
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    restart: always
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "80:80"
    networks:
      - mynet

  mysql:
    container_name: mysql_container
    image: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
    volumes:
      - ~/db/mysql/data:/var/lib/mysql
      - ~/db/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
