"""update illust metadata table

Revision ID: 1bc0e6c174cd
Revises: b9e576d4bc2f
Create Date: 2024-06-22 15:54:54.955864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bc0e6c174cd'
down_revision: Union[str, None] = 'b9e576d4bc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('illust_metadata', sa.Column('original_image', sa.String(length=255), nullable=False))
    op.add_column('illust_metadata', sa.Column('badge_image', sa.String(length=255), nullable=False))
    op.drop_column('illust_metadata', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('illust_metadata', sa.Column('image', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('illust_metadata', 'badge_image')
    op.drop_column('illust_metadata', 'original_image')
    # ### end Alembic commands ###
