"""add IllustMetadataTable

Revision ID: b9e576d4bc2f
Revises: a65d06192325
Create Date: 2024-06-21 19:39:38.592968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e576d4bc2f'
down_revision: Union[str, None] = 'a65d06192325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illust_metadata',
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('genre', sa.Enum('Vehicle', 'Weather_Season', 'Animal', 'Prefectures', 'Sports', 'Symbols', 'Other', name='genreenum'), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('contour_points', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illust_metadata')
    # ### end Alembic commands ###
